use_frameworks!

platform :ios, '8.0'

target 'ZKLagMonitor_Example' do
  pod 'ZKLagMonitor', :path => '../'

  target 'ZKLagMonitor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
